a = input ('digite algo')
print ('o tipo primitivo desse valor é ', type(a))
print ('só tem espaço?', a.isspace())
print ('É um número?', a.isnumeric())
print ('É alfabetico?', a.isalpha())
print ('É alfanúmerico', a.isalnum())
print ('Éstá em maiúsculas?', a.isupper())
print ('Está em minúsculas?', a.islower())
print('Está capitalizada', a.istitle())
